---
title: Biodiversity footprinting for the energy sector
subtitle: Master's thesis
author: Elke Michlmayr
format:
  html:
    code-fold: true
  pdf:
    number-sections: true
    include-in-header: titlepage.tex
    keep-tex: true
    mainfont: "Georgia"
    sansfont: "Helvetica"
    monofont: "Courier New"
execute:
  warning: false
  message: false
lang: en
bibliography: bibliography.bib
csl: apa-no-ampersand.csl
---


```{=latex}
\section*{Abstract}
Renewable energy is critical for climate mitigation.
```


# Disposition (2000 - 3000 words)

## Topic

Biodiversity footprinting for the energy sector: A high-level assessment of the climate impact of the energy sector globally and in Switzerland using an LCA approach

## Research questions and hypotheses

## Research aims

- Perform literature review of existing work on this topic 
- Investigate if and how satellite data can be employed for this project

## Literature study: current state of research

### Methodologies for biodiversity in LCA

@Winter2017 provide a comprehensive review of the state of biodiversity integration into Life Cycle Assessment (LCA). Their analysis of 119 biodiversity indicators reveals a gap in taxonomic coverage. While species and ecosystem diversity are relatively well-represented, genetic diversity is neglected. The study identifies a major disconnect between ecological theory and industrial practice, noting that models like ReCiPe focus on a narrow subset of pressures, and often use "species richness" synonymously with biodiversity. To bridge these gaps, the authors recommend systemic modifications across all four phases of the LCA process. Inventory data for missing pressures such as noise, artificial light, and odour should be developed. Impact assessment models that capture all three levels of biodiversity (ecosystem, species, genetics) through improved regionalisation and higher spatial resolution should be adopted.

@Deuber2026 proposes an enhanced hybrid framework to assess the biodiversity footprint of Swiss national consumption by integrating LC-IMPACT endpoint modeling with recent GLAM midpoint indicators. While prior assessments focused narrowly on land use, this approach expands coverage to stressors like global warming and terrestrial acidification. It allows for gradual updates in the methodology once improved GLAM midpoint indicators (e.g. for alien species introductions, marine acidification, or functional diversity) become available. For inventory modelling, the EE IO TRAIL (Environmentally Extended Input-Output Analysis using Trade Information and LCA) method is used in the Swiss context and the EE MRIO (Multi-Regional Input-Output) models are suggested for tracing global supply chains. The author advocates for sub-national regionalization of inventories to better identify and protect biodiversity hotspots. 

### Biodiversity and satellite data

@Goetz2025 evaluate how different agricultural production systems affect biodiversity under intensified land use for permanent crops such as coffee, cocoa, and oil palm. The study integrates regionalized environmental and biodiversity impact characterization factors with crop-specific land-use and productivity data to provide a spatially explicit assessment of ecological impacts across production systems.

@posth2024bio introduce the Bio-Value-at-Risk (BioVaR) framework, which uses geospatial analysis to provide a bottom-up quantification of biodiversity risks by overlaying remote sensing data with spatial footprints of corporate assets. The underlying IBLG model structures the spatial association between operational activities and environmental impacts across four scales: Internal (within the property boundary), Bordering (immediate neighbourhood), Landscape (up to 1,000 km), and Global. High-resolution data from Landsat and Copernicus is used to calculate site-specific biodiversity loss footprints based on indicators such as Mean Species Abundance (MSA) as defined in the GLOBIO model by @schipper2020projecting or Potentially Disappeared Fraction (PDF) as used in LCA. Mapping the findings into a financial dimension via calibrated cost functions allows to translate physical ecological damage into site-specific financial costs. It can then be consistently aggregated for corporate risk management and investment portfolio analysis.

@Hauser2025 define seven guiding principles for leveraging satellite remote sensing in corporate disclosure. Companies should clearly define the area, time period, and activities being assessed, including indirect effects beyond their own sites. They should cover key aspects of ecosystems using a small set of well defined LCA impact categories. Changes over time should be tracked to separate natural variation from human impacts. Environmental changes should be linked to company operations. Companies should assess how business performance depends on ecosystems, including related risks, and measure direct, indirect, and cumulative impacts across operations and supply chains. Finally, companies should consider the cross dependencies between impact categories.

### Analysis of the effects of energy production on biodiversity

@Gong2025 measure the land-use induced biodiversity impacts for over 40,000 renewable energy plants by integrating spatial Threat-Abatement STAR (STAR$_T$) scores introduced by @mair2021metric with high-resolution satellite imagery to verify exact project footprints. The study found that solar power generates the largest aggregate biodiversity impact because of its extensive land requirements. Hydropower plants are disproportionately sited in the world's most biodiversity-sensitive locations. Total biodiversity loss from these installations has risen sharply over the last two decades, primarily driven by increased land use per project. It is highly concentrated, with just 1% of plants responsible for nearly 70% of the overall impact. Corporate finance applications reveal that ownership and financing structures significantly influence siting decisions. The researchers estimate that the ongoing expansion of renewable capacity could increase these impacts to a scale equivalent to Canada’s total land biodiversity value by 2030 and point out the need for targeted siting policies and stricter environmental safeguards.

@MCMANAMAY2021109234 evaluate the global biodiversity implications of alternative electrification strategies by developing a spatially explicit framework that combines high-resolution energy density estimates for ten renewable and conventional technologies with species richness data for birds, amphibians, mammals, and fish. The biodiversity Footprint is measured as species impacted per GWh of energy produced. Biomass-powered electricity is identified as the most damaging to biodiversity, because its low energy density requires massive land assets that can overlap with biodiversity hotspots. Solar technologies are found to be land-sparing, because their high energy density allows global electricity demand to be met within a much smaller total footprint despite causing localized land degradation. The researchers find what they call a "protected area paradox", where strictly avoiding development on protected lands actually increases total biodiversity loss. Excluding energy-dense areas forces infrastructure into less optimal lower-density regions, consequently requiring a significantly larger geographical area to meet the same global energy needs. The authors recommend consolidating large-scale solar and wind development instead of patchy deployment, as it could significantly lessen the burden on global biodiversity.

@FONTANIER2025145735 evaluate the application of three biodiversity footprinting methods (Global Biodiversity Score, Product Biodiversity Footprint, and Site Biodiversity Footprint) to the French nuclear fleet, identifying water use for cooling and upstream value chain activities, such as uranium mining, as the primary drivers of biodiversity impact. The study demonstrates that while these tools are valuable for identifying hotspots, they require significant resources for data collection and specialized internal expertise. The authors advocate for greater standardisation and transparency in biodiversity modeling to enhance the reliability and comparability of footprint results across industrial sectors.

@wang2025environmental study PV installations in an alpine meadow on the eastern Tibetan Plateau and find that air temperature rises in daytime and summer, but drops at night and in winter. Soil under panels is colder and drier, while gaps between panels are colder and wetter, extending the frozen period by roughly 50 days and slowing moisture loss up to 3.5×. These shifts alter local energy and water balances, warranting further studies to evaluate the long-term impacts on vegetation dynamics and permafrost processes.

## Gap analysis

### Gaps in the field of research
### Motivation for the research 
### Justification of the added scientific value for the field of study

## Materials and methods

## Expected results

## Risk assessment

There is a risk that the work will be taken out of context and used as an argument against renewable energy.

## Project schedule

## Budget plan

The will not be any budgetary costs.

# References

